In [15]:

import numpy as np
import matplotlib.pyplot as plt


In [16]:

def calculate_file_entropy(file_data):
    """Calculate Shannon entropy of a binary file."""
    byte_counts = np.bincount(np.frombuffer(file_data, dtype=np.uint8), minlength=256)
    probabilities = byte_counts / len(file_data)
    probabilities = probabilities[probabilities > 0]  # Filter non-zero probabilities
    print( probabilities )
    return -np.sum(probabilities * np.log2(probabilities))



In [17]:




packed_binary = np.random.choice( [0, 1], size=1024, p=[0.4, 0.6])
print( packed_binary.shape )

packed_binary[:100]


(1024,)


array([1, 1, 1, 0, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 0, 1, 1, 0, 1, 1, 0,
       1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0, 0, 1, 0,
       1, 1, 1, 1, 0, 1, 1, 1, 1, 1, 0, 1, 1, 1, 0, 0, 0, 0, 1, 0, 1, 1,
       0, 1, 1, 1, 1, 0, 1, 0, 0, 0, 1, 1, 0, 1, 0, 0, 1, 1, 0, 1, 0, 1,
       1, 1, 1, 0, 0, 1, 1, 1, 1, 1, 1, 0])

In [18]:

file_data = packed_binary.tobytes()
file_data


b'\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x01\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x00\x01\x

In [19]:

byte_counts = np.bincount(
                 np.frombuffer(file_data, dtype=np.uint8), 
                 minlength=256
)
print( byte_counts.shape )
byte_counts


(256,)


array([7578,  614,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,    0,    0,    0,    0,
          0,    0,    0,    0,    0,    0,    0,   

In [20]:

print( len( file_data )  )

probabilities = byte_counts / len( file_data )

probabilities



8192


array([0.92504883, 0.07495117, 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.        ,
       0.        , 0.        , 0.        , 0.        , 0.     

In [21]:

probabilities = probabilities[probabilities > 0]  
probabilities


array([0.92504883, 0.07495117])

In [22]:

print( probabilities )


[0.92504883 0.07495117]


In [23]:


-np.sum(probabilities * np.log2(probabilities))


0.3841345422382467


## Full example


In [24]:

def calculate_file_entropy(file_data):
    """Calculate Shannon entropy of a binary file."""
    byte_counts = np.bincount(np.frombuffer(file_data, dtype=np.uint8), minlength=256)
    probabilities = byte_counts / len(file_data)
    probabilities = probabilities[probabilities > 0]  # Filter non-zero probabilities
    print( probabilities )
    return -np.sum(probabilities * np.log2(probabilities))

# Simulated packed malware data (low entropy binary)

packed_binary = np.random.choice([0, 1], size=1024, p=[0.8, 0.2])
entropy       = calculate_file_entropy(packed_binary.tobytes())

# Threshold for detecting packed binaries
threshold = 4.0
is_packed = entropy < threshold
print(f"Entropy: {entropy:.4f}")
print(f"Is the binary packed malware? {is_packed}")


[0.9765625 0.0234375]
Entropy: 0.1603
Is the binary packed malware? True
